---
title: "Get ADHD medications from OpenPrescribing Hospital (SCMD)"
format: html
---

```{r}
#| label: setup
#| echo: false
library(DBI)
library(bigrquery)
library(dplyr)
library(dbplyr)
library(here)
library(tidyverse)
library(opencodecounts)

source(here("functions", "ophr.R"))

# ADHD medication codelist URLs from OpenCodelists
adhd_codelist_urls <- list(
  methylphenidate = "https://www.opencodelists.org/codelist/user/kayleepn/methylphenidate-dmd/2affab72/",
  lisdexamfetamine = "https://www.opencodelists.org/codelist/user/kayleepn/lisdexamfetamine-dmd/6e61987e/",
  dexamfetamine = "https://www.opencodelists.org/codelist/user/kayleepn/dexamfetamine-dmd/20807ee9/",
  atomoxetine = "https://www.opencodelists.org/codelist/user/kayleepn/atomoxetine-dmd/529f6553/",
  guanfacine = "https://www.opencodelists.org/codelist/user/kayleepn/guanfacine-dmd/3c42b214/"
)

```

# Connect to BitQuery

```{r}
#| label: connect-bq
con <- connect_scmd()
```

# Preview tables from SCMD pipeline from Louis

```{r}
#| label: check-scmd-pipeline-tables
dplyr::tbl(con, "scmd_processed")
dplyr::tbl(con, "dose")
dplyr::tbl(con, "ingredient_quantity")
dplyr::tbl(con, "ddd_quantity")
```

# Get list of codelists

```{r}
#| label: get-codelists
# Get ADHD medication codelists from OpenCodelists
codelists <- purrr::map(
  adhd_codelist_urls,
  ~ get_codelist(.x)
)

codelists |> 
  map(as_tibble) |> 
  bind_rows(.id = "codelist") |> 
  write_csv(here("codelists", "adhd-dmd-codelists.csv"))
```

# Extract all VMP codes

```{r}
#| label: get-vmp-codes

# Extract VMP codes from codelists (filter to VMP entries only)
vmp_codes <- codelists |>
  purrr::map(~ as_tibble(.x) |> 
  filter(str_detect(term, "\\(VMP\\)"))) |>
  bind_rows() |>
  pull(code) |>
  as.character()
```

# Download data for selected VMP codes

```{r}
#| label: get-hospital-prescribing

df_oph_scmd_processed <- get_scmd_prescribing(
  con,
  "scmd_processed",
  vmp_codes
) |>
  collect()

df_oph_dose <- get_scmd_prescribing(
  con,
  "dose",
  vmp_codes
) |>
  collect()

df_oph_ingredient_quantity <- get_scmd_prescribing(
  con,
  "ingredient_quantity",
  vmp_codes
) |>
  collect()

df_oph_ddd_quantity <- get_scmd_prescribing(
  con,
  "ddd_quantity",
  vmp_codes
) |>
  collect()
```

# Get trusts

```{r}
#| label: get-hospital-orgs

df_trusts <- get_scmd_trusts(con) |>
  collect()

```

# Write data

```{r}
#| label: write-data

write_csv(
  arrange(df_oph_scmd_processed, desc(year_month), vmp_name, ods_code),
  here("output", "openprescribing-hospitals", "adhd_scmd_processed.csv")
)

write_csv(
  arrange(df_oph_dose, desc(year_month), vmp_name, ods_code),
  here("output", "openprescribing-hospitals", "adhd_scmd_dose.csv")
)

write_csv(
  arrange(df_oph_ingredient_quantity, desc(year_month), vmp_name, ods_code),
  here("output", "openprescribing-hospitals", "adhd_scmd_ingredient_quantity.csv")
)

write_csv(
  arrange(df_oph_ddd_quantity, desc(year_month), vmp_name, ods_code),
  here("output", "openprescribing-hospitals", "adhd_scmd_df_oph_ddd_quantity.csv")
)

write_csv(
  arrange(df_trusts, ods_code),
  here("output", "openprescribing-hospitals", "scmd_trusts.csv")
)
```
